src/Din/Controllers/AuthenticationController.cs
using System.Threading.Tasks;
using Din.Data.Entities;
using Din.Service.Services.Interfaces;
using Din.Service.Utils;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Din.Controllers
{
    public class AuthenticationController : BaseController
    {
        #region injections

        private readonly IAuthService _service;

        #endregion injections

        #region constructors

        public AuthenticationController(IAuthService service)
        {
            _service = service;
        }

        #endregion constructors

        #region endpoints

        [HttpPost, AllowAnonymous]
        public async Task<IActionResult> LoginAsync(string username, string password)
        {
            try
            {
                var loginResult = await _service.LoginAsync(username, password);

                await HttpContext.SignInAsync(loginResult);

                await _service.LogLoginAttempt(username, GetClientUaString(), GetClientIp(), LoginStatus.Success);
                return RedirectToAction("Index", "Main");
            }
            catch (LoginException e)
            {
                await _service.LogLoginAttempt(username, GetClientUaString(), GetClientIp(), LoginStatus.Failed);
                return BadRequest(new {item = e.Identifier, message = e.Message});
            }
        }

        [HttpGet, Authorize]
        public async Task<IActionResult> LogoutAsync()
        {
            await HttpContext.SignOutAsync();
            HttpContext.Session.Clear();
            return RedirectToAction("Exit", "Main");
        }

        #endregion endpoints
    }
}

src/Din/Controllers/MainController.cs
using System.Threading.Tasks;
using Din.Service.Clients.Concrete;
using Din.Service.Generators.Interfaces;
using Din.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace Din.Controllers
{
    public class MainController : BaseController
    {
        #region injections

        private readonly IMediaGenerator _generator;

        #endregion injections

        #region constructors

        public MainController(IMediaGenerator generator)
        {
            _generator = generator;
        }

        #endregion constructors

        #region endpoints

        [HttpGet, AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            if (HttpContext.User.Identity.AuthenticationType == null) return View("Index");
            var model = new MediaViewModel {Media = await _generator.GenerateBackgroundImages()};
            return View("Home", model);
        }

        public async Task<IActionResult> Exit()
        {
            return View("Logout", new MediaViewModel {Media = await _generator.GenerateGif(GiphyTag.Bye)});
        }

        #endregion endpoints
    }
}

src/Din/Views/Main/Home.cshtml
@{
    await Html.RenderPartialAsync("~/Views/Main/Partials/_CarouselBackground.cshtml");
}
<div class="container header">
    <a href="https://paypal.me/danenaebers" class="donate-container rounded" data-toggle="tooltip" data-placement="bottom" title="Geef die jongen een snicker">
        <i class="fas fa-money-check-alt"></i>
        <p>Donate</p>
    </a>
    <div class="menu menu--closed">
        <i class="fas fa-bars menu-button"></i>
        <div class="items items--hidden">
            <a href="" class="account-btn">Account<i class="fas fa-user"></i></a>
            @if (Context.User.IsInRole("Admin"))
            {
                <a href="@Url.Action("Index", "Admin")">Admin Panel<i class="fas fa-terminal"></i></a>
            }
            <a href="@Url.Action("LogoutAsync", "Authentication")">Logout<i class="fas fa-sign-out-alt"></i></a>
        </div>
    </div>
</div>
<div class="main-page-content container">
    <div class="row">
        <div class="col-sm-4">
            <div class="app-container" data-toggle="modal" data-target="#add-movie">
                <i class="fa fa-film"></i>
                <h3>Add Movie</h3>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="app-container" id="launch-client">
                <i class="fa fa-play-circle"></i>
                <h3>Launch Client</h3>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="app-container" data-toggle="modal" data-target="#add-tvshow">
                <i class="fa fa-tv"></i>
                <h3>Add Tv Show</h3>
            </div>
        </div>
    </div>
</div>
@{
    await Html.RenderPartialAsync("~/Views/Main/Partials/_AddMovie.cshtml");
    await Html.RenderPartialAsync("~/Views/Main/Partials/_AddTvShow.cshtml");
}
<div class="ajax-div"></div>
<div class="lds-ring">
    <div></div>
    <div></div>
    <div></div>
    <div></div>
</div>

src/Din/Views/Main/Index.cshtml
<div id="particles">
    <div class="container">
        <div class="index">
            <h1 id="title">DIN</h1>
            <br />
            <h3 id="subtitle">Movies are awesome!</h3>
            <div class="login-form">
                <form id="login-form">
                    <div id="username-input" class="form-group log-status">
                        <input type="text" class="form-control" placeholder="Username" name="username" id="username">
                    </div>
                    <div id="password-input" class="form-group log-status">
                        <input type="password" class="form-control" placeholder="Password" name="password" id="password">
                    </div>
                    <span class="alert"></span>
                    <button type="submit" class="log-btn">Log in</button>
                </form>
            </div>
        </div>
        <div class="lds-ring"><div></div><div></div><div></div><div></div></div>    </div>
</div>

src/Din/Views/Main/Logout.cshtml
@model Din.ViewModels.MediaViewModel

<div class="gif-container">
    <div class="msg-container">
        <h3>smell ya later</h3>
    </div>
    <img src="@Model.Media.Gif.Data.ImageOriginalUrl" />
</div>

@section scripts {
    <script>
        window.setTimeout(function(){
            window.location.href='https://thedin.nl';
        }, 5000);
    </script>
}