src/Din/ViewModels/ResultViewModel.cs
namespace Din.ViewModels
{
    public class ResultViewModel
    {
        public string Title { get; set; }
        public string TitleColor { get; set; }
        public string Message { get; set; }
    }
}

src/Din/ViewModels/SearchResultViewModel.cs
using System.Collections.Generic;
using TMDbLib.Objects.Search;

namespace Din.ViewModels
{
    public class SearchResultViewModel<TIdentifier, TSearchType> where TSearchType : SearchBase
    {
        public IEnumerable<TIdentifier> CurrentCollection { get; set; }
        public ICollection<TSearchType> QueryCollection { get; set; }

    }
}

src/Din/Controllers/MainController.cs
using System.Threading.Tasks;
using Din.Service.Clients.Concrete;
using Din.Service.Generators.Interfaces;
using Din.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Authorization;

namespace Din.Controllers
{
    public class MainController : BaseController
    {
        #region injections

        private readonly IMediaGenerator _generator;

        #endregion injections

        #region constructors

        public MainController(IMediaGenerator generator)
        {
            _generator = generator;
        }

        #endregion constructors

        #region endpoints

        [HttpGet, AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            if (HttpContext.User.Identity.AuthenticationType == null) return View("Index");
            var model = new MediaViewModel {Media = await _generator.GenerateBackgroundImages()};
            return View("Home", model);
        }

        public async Task<IActionResult> Exit()
        {
            return View("Logout", new MediaViewModel {Media = await _generator.GenerateGif(GiphyTag.Bye)});
        }

        #endregion endpoints
    }
}

src/Din/Views/Main/Partials/_AddMovie.cshtml
 <div id="add-movie" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="custom-modal-header">
                <i class="fas fa-times" data-dismiss="modal"></i>
                <h3>Add A Movie</h3>
            </div>
            <div class="modal-body">
                <p>Enter the name of the movie you want to add</p>
                <form id="search-movie-form">
                    <i class="fas fa-search"></i>
                    <input type="search" id="search" class="search-movie" name="searchQuery" placeholder="Search..." />
                    <span class="alert">Why leave it empty?</span>
                    <input id="submit-button" type="submit"  value="search"/>
                </form>
             </div>
         </div>
     </div>
 </div>

src/Din/Views/Main/Partials/_AddResult.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json

@model Din.ExternalModels.ViewModels.AddContentResultModel

<div id="content-added" class="modal fade ajax-div" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="custom-modal-header">
                <i class="fas fa-times" data-dismiss="modal"></i>
                <h3 style="color: @Model.TitleColor" id="modal-title">@Model.Title</h3>
            </div>
            <div class="modal-body">
                <p id="modal-message">@Model.Message</p>
            </div>
        </div>
    </div>
</div>

src/Din/Views/Main/Partials/_AddTvShow.cshtml
<div id="add-tvshow" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="custom-modal-header">
                <i class="fas fa-times" data-dismiss="modal"></i>
                <h3>Add A Tv Show</h3>
            </div>
            <div class="modal-body">
                <p>Enter the name of the Tv Show you want to add</p>
                <form id="search-show-form">
                    <i class="fas fa-search"></i>
                    <input type="search" id="search" class="search-show" name="searchQuery" placeholder="Search..." />
                    <span class="alert">Why leave it empty?</span>
                    <input id="submit-button" type="submit" value="search" />
                </form>
            </div>
        </div>
    </div>
</div>

src/Din/Views/Main/Partials/_CarouselBackground.cshtml
@using Din.Service.Clients.ResponseObjects
@model Din.ViewModels.MediaViewModel


<div class="carousel slide" data-ride="carousel">
    <div class="carousel-inner" role="listbox">
        @{
            var image = Model.Media.BackgroundImageCollection.First();
            var collectionCopy = new List<UnsplashItem>(Model.Media.BackgroundImageCollection);
            <div class="carousel-item active"><img src="@image.FileTypes.Regular" /></div>
            collectionCopy.Remove(image);
            foreach (var i in collectionCopy)
            {
                <div class="carousel-item"><img src="@i.FileTypes.Regular" /></div>
            }
        }
    </div>
</div>

src/Din/Views/Main/Partials/_MovieResults.cshtml
@using Newtonsoft.Json

@model Din.ViewModels.SearchResultViewModel<int, TMDbLib.Objects.Search.SearchMovie>

@if (Model.QueryCollection.Count.Equals(0))
{
    <div id="search-results-failed" class="modal fade ajax-div" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="custom-modal-header">
                    <i class="fas fa-times" data-dismiss="modal"></i>
                    <h3 id="modal-title">No movies where found</h3>
                </div>
                <div class="modal-body">
                    <p id="modal-message">Your search query resulted in 0 hits 😵<br/>Check for typo's</p>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div id="search-results" class="modal fade ajax-div" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="card-frame">
                        @foreach (var movie in Model.QueryCollection)
                        {
                            var date = Convert.ToDateTime(movie.ReleaseDate).Year;
                            var posterPath = "https://image.tmdb.org/t/p/w185_and_h278_bestv2" + movie.PosterPath;

                            <div class="item poster card">
                                <div class="image">
                                    @{
                                        if (string.IsNullOrEmpty(movie.PosterPath))
                                        {
                                            <img class="poster" sizes="185px" src="~/images/not-found.png" )/>
                                        }
                                        else
                                        {
                                            <img class="poster" sizes="185px" src="@posterPath"/>
                                        }
                                    }
                                </div>
                                <div class="info">
                                    <p class="flex">
                                        <a title="@movie.Title">@movie.Title</a>
                                        <span class="vote_avarage">
                                            @movie.VoteAverage
                                            <i class="fas fa-star"></i>
                                        </span>
                                    </p>
                                    <p class="flex">
                                        <span>
                                            <i class="far fa-calendar-alt"></i>
                                            @date.ToString()
                                        </span>
                                    </p>
                                    <p class="overview">
                                        @movie.Overview
                                    </p>
                                    <div class="add-button">
                                        @{
                                            if (Model.CurrentCollection.Contains(movie.Id))
                                            {
                                                <button disabled type="button" class="btn">Already Exists</button>
                                            }
                                            else
                                            {
                                                <button data-model="@JsonConvert.SerializeObject(movie)" class="btn add-movie">Add Movie</button>
                                                <input class="selected-movie" name="selected-movie"/>
                                            }
                                        }
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}

src/Din/Views/Main/Partials/_Result.cshtml
@model Din.ViewModels.ResultViewModel

<div id="result-dialog" class="modal fade ajax-div" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="custom-modal-header">
                <i class="fas fa-times" data-dismiss="modal"></i>
                <h3 style="color: @Model.TitleColor" id="modal-title">@Model.Title</h3>
            </div>
            <div class="modal-body">
                <p id="modal-message">@Model.Message</p>
            </div>
        </div>
    </div>
</div>

src/Din/Views/Main/Partials/_SearchResults.cshtml
@using Microsoft.AspNetCore.Http
@using Newtonsoft.Json

@model Din.ExternalModels.ViewModels.SearchResultsModel

@if (Context.Session.GetString("User") != null)
{
    if (Model.QueryResult.Count.Equals(0))
    {
        <div id="search-results-failed" class="modal fade ajax-div" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="custom-modal-header">
                        <i class="fas fa-times" data-dismiss="modal"></i>
                        <h3 id="modal-title">No movies where found</h3>
                    </div>
                    <div class="modal-body">
                        <p id="modal-message">Your search query resulted in 0 hits 😵<br/>Check for typo's</p>
                    </div>
                </div>
            </div>
        </div>
    }
    else
    {
        <div id="search-results" class="modal fade ajax-div" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="custom-modal-header">
                        <i class="fas fa-times" data-dismiss="modal"></i>
                        <h3 id="modal-title">Results</h3>
                    </div>
                    <div class="modal-body">
                        <div class="card-frame">
                            @foreach (var movie in Model.QueryResult)
                            {
                                var date = Convert.ToDateTime(movie.ReleaseDate).Year;
                                var posterPath = "https://image.tmdb.org/t/p/w185_and_h278_bestv2" + movie.PosterPath;

                                <div movie-id="@movie.Id" class="item poster card">
                                    <div class="image">
                                        @{
                                            if (string.IsNullOrEmpty(movie.PosterPath))
                                            {
                                                <img class="poster" sizes="185px" src="~/images/not-found.png" )/>
                                            }
                                            else
                                            {
                                                <img class="poster" sizes="185px" src="@posterPath"/>
                                            }
                                        }
                                    </div>
                                    <div class="info">
                                        <p class="flex">
                                            <a title="@movie.Title">@movie.Title</a>
                                            <span class="vote_avarage">
                                                @movie.VoteAverage
                                                <span class="oi oi-star"></span>
                                            </span>
                                        </p>
                                        <p class="flex">
                                            <span>
                                                <i class="far fa-calendar-alt"></i>
                                                @date.ToString()
                                            </span>
                                        </p>
                                        <p class="overview">
                                            @movie.Overview
                                        </p>
                                        <div class="add-button">
                                            @{
                                                if (Model.CurrentIdList.Contains(movie.Id))
                                                {
                                                    <button disabled type="button" class="btn btn-default">Already Exists</button>
                                                }
                                                else
                                                {
                                                    <button id="@movie.Id" data-model="@JsonConvert.SerializeObject(movie)" class="btn btn-primary add-movie">Add Movie</button>
                                                    <input class="selected-movie" name="selected-movie"/>
                                                }
                                            }
                                        </div>
                                    </div>
                                </div>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
}
else
{
    Url.Action("Index", "Main");
}

src/Din/Views/Main/Partials/_TvShowResults.cshtml
@using Newtonsoft.Json

@model Din.ViewModels.SearchResultViewModel<string, TMDbLib.Objects.Search.SearchTv>

@if (Model.QueryCollection.Count.Equals(0))
{
    <div id="search-results-failed" class="modal fade ajax-div" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="custom-modal-header">
                    <i class="fas fa-times" data-dismiss="modal"></i>
                    <h3 id="modal-title">No Tv Shows where found</h3>
                </div>
                <div class="modal-body">
                    <p id="modal-message">Your search query resulted in 0 hits 😵<br/>Check for typo's</p>
                </div>
            </div>
        </div>
    </div>
}
else
{
    <div id="search-results" class="modal fade ajax-div" role="dialog">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="card-frame">
                        @foreach (var show in Model.QueryCollection)
                        {
                            var date = Convert.ToDateTime(show.FirstAirDate).Year;
                            var posterPath = "https://image.tmdb.org/t/p/w185_and_h278_bestv2" + show.PosterPath;

                            <div class="item poster card">
                                <div class="image">
                                    @{
                                        if (string.IsNullOrEmpty(show.PosterPath))
                                        {
                                            <img class="poster" sizes="185px" src="~/images/not-found.png" )/>
                                        }
                                        else
                                        {
                                            <img class="poster" sizes="185px" src="@posterPath"/>
                                        }
                                    }
                                </div>
                                <div class="info">
                                    <p class="flex">
                                        <a>@show.Name</a>
                                        <span class="vote_avarage">
                                            @show.VoteAverage
                                            <span class="oi oi-star"></span>
                                        </span>
                                    </p>
                                    <p class="flex">
                                        <span>
                                            <i class="far fa-calendar-alt"></i>
                                            @date.ToString()
                                        </span>
                                    </p>
                                    <p class="overview">
                                        @show.Overview
                                    </p>
                                    <div class="add-button">
                                        @{
                                            if (Model.CurrentCollection.Contains(show.Name.ToLower()))
                                            {
                                                <button disabled type="button" class="btn">Already Exists</button>
                                            }
                                            else
                                            {
                                                <button data-model="@JsonConvert.SerializeObject(show)" class="btn add-tvshow">Add Tv Show</button>
                                                <input class="selected-movie" name="selected-movie"/>
                                            }
                                        }
                                    </div>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
}